trigger: none

pool:
  vmImage: ubuntu-latest


stages:
    
    - stage: Lint
      jobs: 
      - job: LintCode
        displayName: Lint
        steps:     
          - script: |
             az bicep build --file ./Training/main.bicep
            name: lint


   
    - stage: Validate
      dependsOn: Lint
      jobs: 
      - job: Validate
        displayName: Validate
        steps:       
          - task: AzureCLI@2
            name: validate
            displayName: validate
            inputs:
              azureSubscription: $(ServiceConnectionName)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az account set --subscription $(subscription)
                az deployment sub validate \
                  --location $(parLocation) \
                  --template-file ./Training/main.bicep \
                  --parameters parLocation=$(parLocation) \
                  --name validate_rg-$(RunNumber)   

    - stage: WhatIf
      dependsOn: Validate
      jobs: 
      - job: WhatIf
        displayName: WhatIf
        steps:       
          - task: AzureCLI@2
            name: whatif
            displayName: whatif
            inputs:
              azureSubscription: $(ServiceConnectionName)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az account set --subscription $(subscription)
                az deployment sub what-if \
                  --location $(parLocation) \
                  --template-file ./Training/main.bicep \
                  --parameters parLocation=$(parLocation) \
                  --name validate_rg-$(RunNumber)   

    - stage: Deploy
      dependsOn: WhatIf
      jobs: 
      - job: Deploy
        displayName: Deploy
        steps:
          - task: AzureCLI@2
            name: deploy
            displayName: deploy
            inputs:
              azureSubscription: $(ServiceConnectionName)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az account set --subscription $(subscription)
                az deployment sub create \
                  --template-file Training/main.bicep \
                  --location $(parLocation) \
                  --parameters parLocation=$(parLocation) \
                  --name create_rg-$(RunNumber)   
                  
